stages:
#    - build
    - docker-dev
    - deploy-to-dev
    - dt-event
    - docker-validated
    - docker-stag
    - release
    - deploy-to-stag
    - regcred-clean
    - dev-clean
    - stag-clean

docker-dev:
  rules:
      - if: $CI_COMMIT_TAG == null
  image: docker:27.2.0
  stage: docker-dev
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 0
    DOCKER_DRIVER: overlay2
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    #important! MTU 1410 makes the MTU packages compatible with the underlying network. Otherwise, it will get stuck in downloads 
    DOCKER_DAEMON_OPTIONS: "--insecure-registry=$CI_REGISTRY --mtu=1410"
  services:
    - name: docker:27.2.0-dind
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
  before_script:
    - docker info
  script:
    - docker info
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - echo "AUTH_TOKEN=$(sed -nE '$!{:a;N;$!ba;s/\n//g;s/"auth":[^"]*"([^"]*)"/\n\1\nAUTH/g};/^[^\n]*\nAUTH/P;D' ~/.docker/config.json)" >> auth.env
    - cd contentcreator
    - docker build -t $CI_REGISTRY_IMAGE:DEV-CONTENTCREATOR-$CI_PIPELINE_IID .
    - docker push $CI_REGISTRY_IMAGE:DEV-CONTENTCREATOR-$CI_PIPELINE_IID
    - echo "$CI_PIPELINE_IID"
    - cd ../db
    - docker build -t $CI_REGISTRY_IMAGE:DEV-DB-$CI_PIPELINE_IID .
    - docker push $CI_REGISTRY_IMAGE:DEV-DB-$CI_PIPELINE_IID
    - cd ../engine
    - docker build -t $CI_REGISTRY_IMAGE:DEV-ENGINE-$CI_PIPELINE_IID .
    - docker push $CI_REGISTRY_IMAGE:DEV-ENGINE-$CI_PIPELINE_IID
    - cd ../manager/easyTradeManager
    - docker build -t $CI_REGISTRY_IMAGE:DEV-MANAGER-$CI_PIPELINE_IID .
    - docker push $CI_REGISTRY_IMAGE:DEV-MANAGER-$CI_PIPELINE_IID
    - cd ../../problem-operator
    - docker build -t $CI_REGISTRY_IMAGE:DEV-PROBLEMOPERATOR-$CI_PIPELINE_IID .
    - docker push $CI_REGISTRY_IMAGE:DEV-PROBLEMOPERATOR-$CI_PIPELINE_IID
    - cd ../rabbitmq
    - docker build -t $CI_REGISTRY_IMAGE:DEV-RABBITMQ-$CI_PIPELINE_IID .
    - docker push $CI_REGISTRY_IMAGE:DEV-RABBITMQ-$CI_PIPELINE_IID
  artifacts:
        reports:
            dotenv: auth.env

deploy-to-dev:
    rules:
      - if: $CI_COMMIT_TAG == null
    dependencies:
        - docker-dev
    stage: deploy-to-dev
    image: alpine/kubectl:latest
    script:
        - kubectl create secret docker-registry $CI_PROJECT_NAME --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$AUTH_TOKEN
        - kubectl create secret docker-registry $CI_PROJECT_NAME --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD -n dev
        - cd contentcreator
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:DEV-CONTENTCREATOR-$CI_PIPELINE_IID#" $CI_PROJECT_NAME.yaml
        - "kubectl -n dev apply -f $CI_PROJECT_NAME.yaml"
        - cd ../db
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:DEV-DB-$CI_PIPELINE_IID#" $CI_PROJECT_NAME.yaml
        - "kubectl -n dev apply -f $CI_PROJECT_NAME.yaml"
        - cd ../engine
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:DEV-ENGINE-$CI_PIPELINE_IID#" $CI_PROJECT_NAME.yaml
        - "kubectl -n dev apply -f $CI_PROJECT_NAME.yaml"
        - cd ../manager/easyTradeManager
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:DEV-MANAGER-$CI_PIPELINE_IID#" $CI_PROJECT_NAME.yaml
        - "kubectl -n dev apply -f $CI_PROJECT_NAME.yaml"
        - cd ../../problem-operator
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:DEV-PROBLEMOPERATOR-$CI_PIPELINE_IID#" $CI_PROJECT_NAME.yaml
        - "kubectl -n dev apply -f $CI_PROJECT_NAME.yaml"
        - cd ../rabbitmq
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:DEV-RABBITMQ-$CI_PIPELINE_IID#" $CI_PROJECT_NAME.yaml
        - "kubectl -n dev apply -f $CI_PROJECT_NAME.yaml"
        - sleep 10
        - kubectl wait pod --all -l app.kubernetes.io/component=$CI_PROJECT_NAME  -n dev --for=condition=Ready --timeout=300s
        - kubectl delete secret $CI_PROJECT_NAME
        - kubectl delete secret $CI_PROJECT_NAME -n dev
      
docker-validated:
  rules:
      - if: $CI_COMMIT_TAG == null
  image: docker:27.2.0
  stage: docker-validated
  dependencies:
    - docker-dev
    - deploy-to-dev
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 0
    DOCKER_DRIVER: overlay2
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    #important! MTU 1410 makes the MTU packages compatible with the underlying network. Otherwise, it will get stuck in downloads 
    DOCKER_DAEMON_OPTIONS: "--insecure-registry=$CI_REGISTRY --mtu=1410"
  services:
    - name: docker:27.2.0-dind
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
  before_script:
    - docker info
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker pull $CI_REGISTRY_IMAGE:DEV-CONTENTCREATOR-$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE:DEV-CONTENTCREATOR-$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:CONTENTCREATOR-latest
    - docker push $CI_REGISTRY_IMAGE:CONTENTCREATOR-latest
    - docker pull $CI_REGISTRY_IMAGE:DEV-DB-$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE:DEV-DB-$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:DB-latest
    - docker push $CI_REGISTRY_IMAGE:DB-latest
    - docker pull $CI_REGISTRY_IMAGE:DEV-ENGINE-$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE:DEV-ENGINE-$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:ENGINE-latest
    - docker push $CI_REGISTRY_IMAGE:ENGINE-latest
    - docker pull $CI_REGISTRY_IMAGE:DEV-MANAGER-$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE:DEV-MANAGER-$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:MANAGER-latest
    - docker push $CI_REGISTRY_IMAGE:MANAGER-latest
    - docker pull $CI_REGISTRY_IMAGE:DEV-PROBLEMOPERATOR-$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE:DEV-PROBLEMOPERATOR-$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:PROBLEMOPERATOR-latest
    - docker push $CI_REGISTRY_IMAGE:PROBLEMOPERATOR-latest
    - docker pull $CI_REGISTRY_IMAGE:DEV-RABBITMQ-$CI_PIPELINE_IID
    - docker tag $CI_REGISTRY_IMAGE:DEV-RABBITMQ-$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:RABBITMQ-latest
    - docker push $CI_REGISTRY_IMAGE:RABBITMQ-latest

docker-stag:
  image: docker:27.2.0
  stage: docker-stag
  rules:
    - if: $CI_COMMIT_TAG  
  #needs: ["monaco", "init_keptn"]
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 0
    DOCKER_DRIVER: overlay2
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    #important! MTU 1410 makes the MTU packages compatible with the underlying network. Otherwise, it will get stuck in downloads 
    DOCKER_DAEMON_OPTIONS: "--insecure-registry=$CI_REGISTRY --mtu=1410"
  services:
    - name: docker:27.2.0-dind
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
  before_script:
    - docker info
  script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - echo "AUTH_TOKEN=$(sed -nE '$!{:a;N;$!ba;s/\n//g;s/"auth":[^"]*"([^"]*)"/\n\1\nAUTH/g};/^[^\n]*\nAUTH/P;D' ~/.docker/config.json)" >> auth.env
        - docker pull $CI_REGISTRY_IMAGE:CONTENTCREATOR-latest
        - docker tag $CI_REGISTRY_IMAGE:CONTENTCREATOR-latest $CI_REGISTRY_IMAGE:CONTENTCREATOR-$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:CONTENTCREATOR-$CI_COMMIT_TAG
        - docker pull $CI_REGISTRY_IMAGE:DB-latest
        - docker tag $CI_REGISTRY_IMAGE:DB-latest $CI_REGISTRY_IMAGE:DB-$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:DB-$CI_COMMIT_TAG
        - docker pull $CI_REGISTRY_IMAGE:ENGINE-latest
        - docker tag $CI_REGISTRY_IMAGE:ENGINE-latest $CI_REGISTRY_IMAGE:ENGINE-$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:ENGINE-$CI_COMMIT_TAG
        - docker pull $CI_REGISTRY_IMAGE:MANAGER-latest
        - docker tag $CI_REGISTRY_IMAGE:MANAGER-latest $CI_REGISTRY_IMAGE:MANAGER-$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:MANAGER-$CI_COMMIT_TAG
        - docker pull $CI_REGISTRY_IMAGE:PROBLEMOPERATOR-latest
        - docker tag $CI_REGISTRY_IMAGE:PROBLEMOPERATOR-latest $CI_REGISTRY_IMAGE:PROBLEMOPERATOR-$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:PROBLEMOPERATOR-$CI_COMMIT_TAG
        - docker pull $CI_REGISTRY_IMAGE:RABBITMQ-latest
        - docker tag $CI_REGISTRY_IMAGE:RABBITMQ-latest $CI_REGISTRY_IMAGE:RABBITMQ-$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:RABBITMQ-$CI_COMMIT_TAG
  artifacts:
        reports:
            dotenv: auth.env

release_job:
  dependencies:
        - docker-stag
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'

deploy-to-stag:
    dependencies:
        - docker-stag
    stage: deploy-to-stag
    rules:
        - if: $CI_COMMIT_TAG
    image: alpine/kubectl:latest
    script:
        - kubectl create secret docker-registry $CI_PROJECT_NAME --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$AUTH_TOKEN
        - kubectl create secret docker-registry $CI_PROJECT_NAME --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD -n staging
        - cd contentcreator
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:CONTENTCREATOR-$CI_COMMIT_TAG#" $CI_PROJECT_NAME.yaml
        - |
            sed -i "s#namespace: .*#namespace: staging#" $CI_PROJECT_NAME.yaml
        - "kubectl -n staging apply -f $CI_PROJECT_NAME.yaml"
        - cd ../db
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:DB-$CI_COMMIT_TAG#" $CI_PROJECT_NAME.yaml
        - |
            sed -i "s#namespace: .*#namespace: staging#" $CI_PROJECT_NAME.yaml
        - "kubectl -n staging apply -f $CI_PROJECT_NAME.yaml"
        - cd ../engine
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:ENGINE-$CI_COMMIT_TAG#" $CI_PROJECT_NAME.yaml
        - |
            sed -i "s#namespace: .*#namespace: staging#" $CI_PROJECT_NAME.yaml
        - "kubectl -n staging apply -f $CI_PROJECT_NAME.yaml"
        - cd ../manager/easyTradeManager
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:MANAGER-$CI_COMMIT_TAG#" $CI_PROJECT_NAME.yaml
        - |
            sed -i "s#namespace: .*#namespace: staging#" $CI_PROJECT_NAME.yaml
        - "kubectl -n staging apply -f $CI_PROJECT_NAME.yaml"
        - cd ../../problem-operator
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:PROBLEMOPERATOR-$CI_COMMIT_TAG#" $CI_PROJECT_NAME.yaml
        - |
            sed -i "s#namespace: .*#namespace: staging#" $CI_PROJECT_NAME.yaml
        - "kubectl -n staging apply -f $CI_PROJECT_NAME.yaml"
        - cd ../rabbitmq
        - |
            sed -i "s#image: .*#image: $CI_REGISTRY_IMAGE:RABBITMQ-$CI_COMMIT_TAG#" $CI_PROJECT_NAME.yaml
        - |
            sed -i "s#namespace: .*#namespace: staging#" $CI_PROJECT_NAME.yaml
        - "kubectl -n staging apply -f $CI_PROJECT_NAME.yaml"
        - sleep 10
        - kubectl wait pod --all -l app.kubernetes.io/component=$CI_PROJECT_NAME  -n staging --for=condition=Ready --timeout=300s
        - kubectl delete secret $CI_PROJECT_NAME
        - kubectl delete secret $CI_PROJECT_NAME -n staging

regcred-clean:
    rules:
        - when: on_failure
        - if: $CI_COMMIT_TAG == null
    stage: regcred-clean
    image: alpine/kubectl:latest
    script:
        - kubectl delete secret $CI_PROJECT_NAME
    allow_failure: true

dev-clean:
    rules:
        - when: on_failure
        - if: $CI_COMMIT_TAG == null
    stage: dev-clean
    image: alpine/kubectl:latest
    script:
        - kubectl delete secret $CI_PROJECT_NAME -n dev
    allow_failure: true

stag-clean:
    rules:
        - when: on_failure
        - if: $CI_COMMIT_TAG
    stage: stag-clean
    image: alpine/kubectl:latest
    script:
        - kubectl delete secret $CI_PROJECT_NAME -n staging
    allow_failure: true